import { describe, expect, it } from "vitest";
import { buildCurve } from "../pipeline/curve";
import { Tracer } from "../rules/define";
import type { PlanInput } from "../types";

// The returner scenario from docs/research/progression-und-verletzungspraevention.md
// (10 km/wk -> sub-20 5K over 12 months). The research doc's 6-month
// mileage table is hand-authored, not generated by a simple mechanical
// recurrence — the engine's build/deload/restart rules reproduce its
// early weeks closely but drift beyond ~week 8 as small per-week
// differences compound (verified directly: week 11 is 29.0 km here vs.
// 26.0 in the table, an already-3km gap). So this test checks the
// *properties* the rule set is supposed to guarantee (start point, exact
// build-step arithmetic, deload = 80% of the preceding build week,
// post-deload restart from the pre-deload peak, eventual convergence on
// the target, and taper), not a brittle per-week table match.
function baseInput(overrides: Partial<PlanInput> = {}): PlanInput {
  return {
    goal: {
      distanceMeters: 5000,
      targetDate: "2027-08-29",
      targetTimeSeconds: 1200,
    },
    currentWeeklyVolumeKm: 10,
    currentRunsPerWeek: 3,
    longestRecentRunKm: 5,
    availableDaysPerWeek: 4,
    longRunDay: "sunday",
    experience: "beginner",
    safetyScreenCompleted: true,
    startDate: "2026-08-29",
    today: "2026-08-29",
    ...overrides,
  };
}

function weeks(input: PlanInput) {
  return buildCurve(input, new Tracer()).weeks;
}

describe("buildCurve volume progression", () => {
  it("week 1 starts exactly at current weekly volume", () => {
    const [week1] = weeks(baseInput());
    expect(week1?.targetVolumeKm).toBe(10);
  });

  it("matches the research table's first three build weeks exactly (10 -> 12 -> 14)", () => {
    const w = weeks(baseInput());
    expect(w[0]?.targetVolumeKm).toBe(10);
    expect(w[1]?.targetVolumeKm).toBe(12);
    expect(w[2]?.targetVolumeKm).toBe(14);
  });

  it("every 4th week is a deload at exactly 80% of the preceding build week", () => {
    const w = weeks(baseInput());
    for (let i = 3; i < w.length; i += 4) {
      const deloadWeek = w[i];
      const precedingWeek = w[i - 1];
      if (deloadWeek?.isTaper) continue; // taper overrides the 3:1 cycle in the final weeks
      expect(deloadWeek?.isDeload).toBe(true);
      expect(deloadWeek?.targetVolumeKm).toBeCloseTo(
        (precedingWeek?.targetVolumeKm ?? 0) * 0.8,
        5,
      );
    }
  });

  it("resumes after a deload from the pre-deload peak, not the deload value", () => {
    const w = weeks(baseInput());
    // Week 3 (index 2) is the pre-deload peak; week 4 (index 3) deloads;
    // week 5 (index 4) should build from week 3's peak, not week 4's dip.
    const preDeloadPeak = w[2]?.targetVolumeKm ?? 0;
    const postDeloadWeek = w[4]?.targetVolumeKm ?? 0;
    expect(postDeloadWeek).toBeGreaterThan(w[3]?.targetVolumeKm ?? 0);
    expect(postDeloadWeek).toBeCloseTo(preDeloadPeak + 2, 5); // preDeloadPeak (14) < 20km threshold -> +2 step
  });

  it("never lets a non-deload, non-taper week's volume decrease week over week", () => {
    const w = weeks(baseInput());
    for (let i = 1; i < w.length; i++) {
      const current = w[i];
      const previous = w[i - 1];
      if (current?.isDeload || current?.isTaper) continue;
      expect(current?.targetVolumeKm).toBeGreaterThanOrEqual(
        previous?.targetVolumeKm ?? 0,
      );
    }
  });

  it("converges on and holds the 45 km/wk target for a 5K goal, without exceeding it", () => {
    const w = weeks(baseInput());
    for (const week of w) {
      expect(week.targetVolumeKm).toBeLessThanOrEqual(45 + 1e-6);
    }
    const lastBuildWeek = [...w]
      .reverse()
      .find((week) => !week.isDeload && !week.isTaper);
    expect(lastBuildWeek?.targetVolumeKm).toBeCloseTo(45, 5);
  });

  it("never starts a plan below the runner's current volume, even if that exceeds the heuristic target", () => {
    const w = weeks(baseInput({ currentWeeklyVolumeKm: 50 }));
    expect(w[0]?.targetVolumeKm).toBe(50);
    for (const week of w) {
      if (!week.isTaper && !week.isDeload)
        expect(week.targetVolumeKm).toBeGreaterThanOrEqual(50 - 1e-6);
    }
  });

  it("applies a smaller build step throughout when priorStressFracture is reported", () => {
    const cautious = weeks(baseInput({ priorStressFracture: true }));
    const standard = weeks(baseInput());
    // Week 2 is a plain build step off week 1 in both cases.
    const cautiousStep =
      (cautious[1]?.targetVolumeKm ?? 0) - (cautious[0]?.targetVolumeKm ?? 0);
    const standardStep =
      (standard[1]?.targetVolumeKm ?? 0) - (standard[0]?.targetVolumeKm ?? 0);
    expect(cautiousStep).toBeCloseTo(standardStep * 0.8, 5);
  });
});

describe("buildCurve phase gates", () => {
  it("stays in 'base' phase below the tempo volume gate (28 km/wk), outside the always-'race' final weeks", () => {
    const w = weeks(baseInput());
    for (const week of w.slice(0, -4)) {
      if (week.targetVolumeKm < 28) expect(week.phase).toBe("base");
    }
  });

  it("only reaches 'interval' phase once the interval volume gate (42 km/wk) is reached", () => {
    const w = weeks(baseInput());
    for (const week of w) {
      if (week.phase === "interval")
        expect(week.targetVolumeKm).toBeGreaterThanOrEqual(42);
    }
  });

  it("puts the final 4 weeks before targetDate in the 'race' phase regardless of volume", () => {
    const w = weeks(baseInput());
    const lastFour = w.slice(-4);
    for (const week of lastFour) expect(week.phase).toBe("race");
  });
});
